// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TranslateExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "TranslateExtension.100523cd-d9d9-4fdd-9249-460ba5192438";
        public const string Name = "Translate extension";
        public const string Description = @"Translate selected text";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Vladyslav Glushkov";
        public const string Tags = "";
    }
}
